add_rules("mode.release", "mode.debug")
add_requires("cuda", {system=true, configs={utils={"cublas","cusparse","cusolver"}}})
add_requires("tinyobjloader v2.0.0rc13")
add_requires("nlohmann_json 3.11.3")
add_requires("boost 1.85.0")
target("common")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("static")
    set_languages("c++17")
    add_headerfiles("*.h")
    add_files("*.cc", "*.cu")
    add_includedirs(".",{public=true})
    add_cugencodes("compute_75")
    add_cuflags("--std c++17", "-lineinfo")
    add_packages("cuda",{public=true})
    add_packages("tinyobjloader",{public=true})
    add_packages("nlohmann_json",{public=true})
    add_packages("boost", {public=true})
